### PR TITLE
08/02 updates: Bug fixes, defensive checks, grammar updates

### PR DESCRIPTION
**Pull request by Abhijay**
Gruntfile:
- added check for basedOn.namespace to account for TBD basedOns that have a label but no namespace.

Handlebars generateBasedOnHierarchy:
- Fixed error on creating visual tree when Element Value is type ChoiceValue
- For EntryElement Observation, the value of the object is a set of multiple choices. Attempting to retrieve the identifier or label of the list returns a null value.
- Solution is to iteratate over list of choices and add each option as a node individually

Handlebars basedOn Constraint:
- added support for binding strength language

Handlebars dataElement:
- added support for Abstract Elements

### CODE REVIEW

**Comment by Dtphelan1** [comment]
This looks good to me! Great work.

**Review by Dtphelan1 — APPROVED** [review]

**Comment by Dtphelan1** [comment]
After talking together in person, we identified two shortcomings of the previous versions: 
1. The visualization needs a better way of handling choice values. 
2. The search bar wasn't working.

It looks like your updates handle both of these oversights. Looking now for anything else we missed

**Comment by Dtphelan1** [comment]
There's an inconsistency in the specification due to partially done Value definitions and restriction. The inclusion of Value's in some places and not in others lead to some inconsistencies in our visualization. For example, BloodPressure is based on VitalSign, BloodPressure has Quantity as it's value but doesn't display Quantity as a node; conversely, because of partial definitions, BodyHeight is based on VitalSign, BodyHeight  has Quantity as it's value and **does** display Quantity as a node. This is a shortcoming of the model construction for our Viz, but I don't think this issue should slow down a push to the website since it's such an isolated corner case and doesn't break anything. Perhaps we could lodge it as an issue for now? I'd like to know what @gregquinn2001 thinks of this. 

Sandboxed version of the site is on https://abhijay.github.io/

**Comment by gregquinn2001** [comment]
Ok. it took me a minute to figure out that you were talking about in the viz. sorry. I agree that it is a bug and should be logged in jira but I would definitely move forward and get this latest version to the web site. So, your approach sounds perfect @Dtphelan1

**Comment by Abhijay** [comment]
I added a "Value: " prefix to the value nodes. I'll account for the value ambiguity in a later PR as that wasn't critical to the current push. Otherwise. Is this all set to be merged? (for the spec_json2html, the website PR is coming in shortly)

**Comment by Dtphelan1** [comment]
Again, this looks good to merge. Sounds like all other needed changes have been logged as separate issues.

**Pull request merged**
